#ifndef COMMON_H
#define COMMON_H

#define PALETTE_CELL_SIZE_PX 20
#define PALETTE_ROW_COUNT 4
#define PALETTE_COL_COUNT 4
#define PALETTE_WIDTH_PX = PALETTE_CELL_SIZE_PX * PALETTE_ROW_COUNT
#define PALETTE_HEIGHT_PX = PALETTE_CELL_SIZE_PX * PALETTE_COL_COUNT

#endif // COMMON_H
